[project]
name = "get-tpu"
version = "0.1.0"
description = "Simple script to create and manage TPU VMs on GCP"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "typer",
    "rich",
]

[dependency-groups]
dev = [
    "ipdb>=0.13.13",
    "ruff>=0.14.4",
]
